name: Build Vanilla Kernel (llvm)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ramabondanp/android_kernel_common-5.10
          kernel-branch: android12-5.10
          config: gki_defconfig
          arch: arm64
          aosp-clang: false
          aosp-gcc: false
          other-clang-url: https://github.com/llvm/llvm-project/releases/download/llvmorg-23.1.2/LLVM-23.1.2-Linux-X64.tar.xz
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          extra-make-args: '["LLVM=1", "LLVM_IAS=1"]'
