name: Build Vanilla Kernel (LLVM)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ramabondanp/android_kernel_common-5.10
          kernel-branch: android12-5.10
          config: gki_defconfig
          arch: arm64
          aosp-gcc: false
          other-gcc32-url: https://github.com/gcc-mirror/gcc
          other-gcc32-branch: releases/gcc-16
          other-gcc64-url: https://github.com/gcc-mirror/gcc
          other-gcc64-branch: releases/gcc-16
          other-clang-url: https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/06092026/neutron-clang-06092026.tar.zst
          anykernel3: true
