name: Build Vanilla Kernel (clang-r596125)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ramabondanp/android_kernel_common-5.10
          kernel-branch: android12-5.10
          config: gki_defconfig
          arch: arm64
          aosp-clang: false
          aosp-gcc: false
          other-gcc32-url: https://github.com/xiangfeidexiaohuo/GCC-4.9
          other-gcc64-url: https://github.com/xiangfeidexiaohuo/GCC-4.9
          other-gcc32-branch: arm32
          other-gcc64-branch: gcc4.9
          other-clang-url: https://github.com/jaymvictorino/clang-r596125-mirror/releases/download/v0.0.1/linux-x86-refs-heads-mirror-goog-main-llvm-toolchain-source-clang-r596125.tar.gz LLVM=1
          anykernel3: true
          anykernel3-url: https://github.com/osm0sis/AnyKernel3
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          extra-make-args: LLVM=1
