name: Build Vanilla Kernel (clang-r596125)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ramabondanp/android_kernel_common-5.10
          kernel-branch: android12-5.10
          config: gki_defconfig
          arch: arm64
          other-clang-url: https://github.com/jaymvictorino/clang-r596125-mirror/releases/download/v0.0.1/linux-x86-refs-heads-mirror-goog-main-llvm-toolchain-source-clang-r596125.tar.gz
          anykernel3: true
          extra-make-args: "LLVM=1 LLVM_IAS=1"
