name: Build Vanilla Kernel (test)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@v1.10.4
        with:
          kernel-url: https://github.com/ramabondanp/android_kernel_common-5.10
          kernel-branch: android12-5.10
          config: gki_defconfig
          ccache: true
          arch: arm64
          other-clang-url: 'https://github.com/bachnxuan/aosp_clang_mirror/releases/download/clang-r614150-16464736/clang-r614150.tar.gz LLVM=1'
          anykernel3: true
          anykernel3-url: https://github.com/LoggingNewMemory/SuiKernel-anykernel
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          extra-make-args: LLVM=1 LLVM_IAS=1
